"""Loading

Revision ID: 1629adf47af8
Revises: b8cb9255d659
Create Date: 2024-02-22 10:33:22.464469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1629adf47af8'
down_revision = 'b8cb9255d659'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
