"""Modified the Models

Revision ID: 19a8119822e2
Revises: 335d532b4081
Create Date: 2024-02-15 18:36:07.159516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a8119822e2'
down_revision = '335d532b4081'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rest_customers',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id', 'customer_id')
    )
    op.add_column('reviews', sa.Column('star_rating', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('customer_id', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('restaurant_id', sa.String(), nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('reviews', 'restaurant_name')
    op.drop_column('reviews', 'ratings')
    op.drop_column('reviews', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('customer_name', sa.VARCHAR(), nullable=True))
    op.add_column('reviews', sa.Column('ratings', sa.INTEGER(), nullable=True))
    op.add_column('reviews', sa.Column('restaurant_name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'restaurants', ['restaurant_name'], ['name'])
    op.create_foreign_key(None, 'reviews', 'customers', ['customer_name'], ['first_name'])
    op.drop_column('reviews', 'restaurant_id')
    op.drop_column('reviews', 'customer_id')
    op.drop_column('reviews', 'star_rating')
    op.drop_table('rest_customers')
    # ### end Alembic commands ###
