"""Loading

Revision ID: b8cb9255d659
Revises: b40d8370693a
Create Date: 2024-02-22 10:30:21.279465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8cb9255d659'
down_revision = 'b40d8370693a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
